import './globals.css'
import ProfileCard from '../components/Sidebar/ProfileCard'
import Link from 'next/link'
import Providers from './Providers'
import { SearchBar, UserAvatar } from '@/utilities/utilities'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="flex flex-col overflow-hidden">
				<Providers>
					<div className="flex flex-col ">
						<header className="flex items-center justify-between gap-3 bg-black p-3 px-6">
							<div className="flex items-center gap-4">
								<Link
									href="/"
									className="mt-[-10px] text-4xl font-bold text-yellow-500 "
								>
									Venato
								</Link>
								<SearchBar />
							</div>

							<UserAvatar text="SM" />
						</header>
						<div className="flex ">
							<nav className="flex h-screen w-60 min-w-[225px] flex-col justify-between bg-black p-4">
								<div className=" flex flex-col ">
									<div className=" flex flex-col gap-3 pl-2 text-xl text-white">
										<button className=" w-max">Want to Play</button>
										<button className=" w-max">Owned Games</button>
										<button className=" w-max">Consoles </button>
									</div>
								</div>
							</nav>
							<main className="h-[calc(100vh-64.5px)] w-[calc(100%-225px)] overflow-y-auto bg-black text-white ">
								<div className="h-full">{children}</div>
							</main>
						</div>
					</div>
				</Providers>
			</body>
		</html>
	)
}
