import './globals.css'
import ProfileCard from '../components/Sidebar/ProfileCard'
import Link from 'next/link'
import Providers from './Providers'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="flex bg-yellow-200">
				<Providers>
					<nav className="flex flex-col justify-between bg-black w-[15%] min-w-[225px] p-4">
						<div className="container flex flex-col ">
							<div className="mb-4">
								<Link
									href="/"
									className="w-full text-4xl font-bold text-yellow-500"
								>
									Venato
								</Link>
							</div>
							<div className="container flex flex-col gap-3 pl-2 text-xl text-white">
								<button className=" w-max">Want to Play</button>
								<button className=" w-max">Owned Games</button>
								<button className=" w-max">Consoles </button>
							</div>
						</div>
						<ProfileCard />
					</nav>
					<main className="w-[calc(100%-225px)]">{children}</main>
				</Providers>
			</body>
			{/* <body className="flex h-screen bg-[#111313]">
				<nav className="flex flex-col fixed h-screen w-[20%] min-w-[216px] max-w-[300px] justify-between p-2">
					<Sidebar />
				</nav>
				<main className="flex flex-col bg-[#d4ece0] h-screen w-[80%]  overflow-y-scroll ">
					<div className="center-stage w-full h-[80%] bg-[#000]">
						{children}
					</div>
				</main>
			</body> */}
		</html>
	)
}
